// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: activate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qid           int32                  `protobuf:"varint,1,opt,name=qid,proto3" json:"qid,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Arguments     string                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_activate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_activate_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetQid() int32 {
	if x != nil {
		return x.Qid
	}
	return 0
}

func (x *ActivateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ActivateRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ActivateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActivateRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

var File_activate_proto protoreflect.FileDescriptor

const file_activate_proto_rawDesc = "" +
	"\n" +
	"\x0eactivate.proto\x12\x02pb\"\x95\x01\n" +
	"\x0fActivateRequest\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\x05R\x03qid\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\tR\targumentsB\x06Z\x04./pbb\x06proto3"

var (
	file_activate_proto_rawDescOnce sync.Once
	file_activate_proto_rawDescData []byte
)

func file_activate_proto_rawDescGZIP() []byte {
	file_activate_proto_rawDescOnce.Do(func() {
		file_activate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activate_proto_rawDesc), len(file_activate_proto_rawDesc)))
	})
	return file_activate_proto_rawDescData
}

var file_activate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_activate_proto_goTypes = []any{
	(*ActivateRequest)(nil), // 0: pb.ActivateRequest
}
var file_activate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_activate_proto_init() }
func file_activate_proto_init() {
	if File_activate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activate_proto_rawDesc), len(file_activate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activate_proto_goTypes,
		DependencyIndexes: file_activate_proto_depIdxs,
		MessageInfos:      file_activate_proto_msgTypes,
	}.Build()
	File_activate_proto = out.File
	file_activate_proto_goTypes = nil
	file_activate_proto_depIdxs = nil
}
