// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: subscribe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *SubscribeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SubscribeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_subscribe_proto protoreflect.FileDescriptor

const file_subscribe_proto_rawDesc = "" +
	"\n" +
	"\x0fsubscribe.proto\x12\x02pb\"`\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\")\n" +
	"\x11SubscribeResponse\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\x06Z\x04./pbb\x06proto3"

var (
	file_subscribe_proto_rawDescOnce sync.Once
	file_subscribe_proto_rawDescData []byte
)

func file_subscribe_proto_rawDescGZIP() []byte {
	file_subscribe_proto_rawDescOnce.Do(func() {
		file_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscribe_proto_rawDesc), len(file_subscribe_proto_rawDesc)))
	})
	return file_subscribe_proto_rawDescData
}

var file_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscribe_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: pb.SubscribeRequest
	(*SubscribeResponse)(nil), // 1: pb.SubscribeResponse
}
var file_subscribe_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscribe_proto_init() }
func file_subscribe_proto_init() {
	if File_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscribe_proto_rawDesc), len(file_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscribe_proto_goTypes,
		DependencyIndexes: file_subscribe_proto_depIdxs,
		MessageInfos:      file_subscribe_proto_msgTypes,
	}.Build()
	File_subscribe_proto = out.File
	file_subscribe_proto_goTypes = nil
	file_subscribe_proto_depIdxs = nil
}
