// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Maxresults    int32                  `protobuf:"varint,3,opt,name=maxresults,proto3" json:"maxresults,omitempty"`
	Exactsearch   bool                   `protobuf:"varint,4,opt,name=exactsearch,proto3" json:"exactsearch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetMaxresults() int32 {
	if x != nil {
		return x.Maxresults
	}
	return 0
}

func (x *QueryRequest) GetExactsearch() bool {
	if x != nil {
		return x.Exactsearch
	}
	return false
}

type QueryMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qid           int32                  `protobuf:"varint,1,opt,name=qid,proto3" json:"qid,omitempty"`
	Iid           int32                  `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetaResponse) Reset() {
	*x = QueryMetaResponse{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetaResponse) ProtoMessage() {}

func (x *QueryMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetaResponse.ProtoReflect.Descriptor instead.
func (*QueryMetaResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMetaResponse) GetQid() int32 {
	if x != nil {
		return x.Qid
	}
	return 0
}

func (x *QueryMetaResponse) GetIid() int32 {
	if x != nil {
		return x.Iid
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qid           int32                  `protobuf:"varint,1,opt,name=qid,proto3" json:"qid,omitempty"`
	Iid           int32                  `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Item          *QueryResponse_Item    `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetQid() int32 {
	if x != nil {
		return x.Qid
	}
	return 0
}

func (x *QueryResponse) GetIid() int32 {
	if x != nil {
		return x.Iid
	}
	return 0
}

func (x *QueryResponse) GetItem() *QueryResponse_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type QueryResponse_Item struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Identifier    string                        `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Text          string                        `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Subtext       string                        `protobuf:"bytes,3,opt,name=subtext,proto3" json:"subtext,omitempty"`
	Icon          string                        `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Provider      string                        `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Score         int32                         `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Fuzzyinfo     *QueryResponse_Item_FuzzyInfo `protobuf:"bytes,7,opt,name=fuzzyinfo,proto3" json:"fuzzyinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse_Item) Reset() {
	*x = QueryResponse_Item{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse_Item) ProtoMessage() {}

func (x *QueryResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse_Item.ProtoReflect.Descriptor instead.
func (*QueryResponse_Item) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2, 0}
}

func (x *QueryResponse_Item) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *QueryResponse_Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QueryResponse_Item) GetSubtext() string {
	if x != nil {
		return x.Subtext
	}
	return ""
}

func (x *QueryResponse_Item) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *QueryResponse_Item) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *QueryResponse_Item) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryResponse_Item) GetFuzzyinfo() *QueryResponse_Item_FuzzyInfo {
	if x != nil {
		return x.Fuzzyinfo
	}
	return nil
}

type QueryResponse_Item_FuzzyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Positions     []int32                `protobuf:"varint,3,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse_Item_FuzzyInfo) Reset() {
	*x = QueryResponse_Item_FuzzyInfo{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse_Item_FuzzyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse_Item_FuzzyInfo) ProtoMessage() {}

func (x *QueryResponse_Item_FuzzyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse_Item_FuzzyInfo.ProtoReflect.Descriptor instead.
func (*QueryResponse_Item_FuzzyInfo) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *QueryResponse_Item_FuzzyInfo) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QueryResponse_Item_FuzzyInfo) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *QueryResponse_Item_FuzzyInfo) GetPositions() []int32 {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x02pb\"\x84\x01\n" +
	"\fQueryRequest\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"maxresults\x18\x03 \x01(\x05R\n" +
	"maxresults\x12 \n" +
	"\vexactsearch\x18\x04 \x01(\bR\vexactsearch\"7\n" +
	"\x11QueryMetaResponse\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\x05R\x03qid\x12\x10\n" +
	"\x03iid\x18\x02 \x01(\x05R\x03iid\"\x93\x03\n" +
	"\rQueryResponse\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\x05R\x03qid\x12\x10\n" +
	"\x03iid\x18\x02 \x01(\x05R\x03iid\x12*\n" +
	"\x04item\x18\x03 \x01(\v2\x16.pb.QueryResponse.ItemR\x04item\x1a\xb1\x02\n" +
	"\x04Item\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\asubtext\x18\x03 \x01(\tR\asubtext\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12>\n" +
	"\tfuzzyinfo\x18\a \x01(\v2 .pb.QueryResponse.Item.FuzzyInfoR\tfuzzyinfo\x1aU\n" +
	"\tFuzzyInfo\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1c\n" +
	"\tpositions\x18\x03 \x03(\x05R\tpositionsB\x06Z\x04./pbb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_query_proto_goTypes = []any{
	(*QueryRequest)(nil),                 // 0: pb.QueryRequest
	(*QueryMetaResponse)(nil),            // 1: pb.QueryMetaResponse
	(*QueryResponse)(nil),                // 2: pb.QueryResponse
	(*QueryResponse_Item)(nil),           // 3: pb.QueryResponse.Item
	(*QueryResponse_Item_FuzzyInfo)(nil), // 4: pb.QueryResponse.Item.FuzzyInfo
}
var file_query_proto_depIdxs = []int32{
	3, // 0: pb.QueryResponse.item:type_name -> pb.QueryResponse.Item
	4, // 1: pb.QueryResponse.Item.fuzzyinfo:type_name -> pb.QueryResponse.Item.FuzzyInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
